# Generated by Django 3.2.5 on 2021-07-29 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_promotion_product_promotions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
    ]
